name: "zentao"                                #plugin名
and: true                                     #rules规则，true表示所有rule匹配则返回true并打印output，false表示只要有一个rule匹配就返回true并打印output
rules:                                        #rules
- method: GET                                 #http请求方式，支持GET和POST
  path: "/zentao/index.php?mode=getconfig"    #http请求路径
  follow_redirects: false                     #是否重定向
  headers:                                    #头部信息
    Accept: "null"
    Accept-Encoding: "null"
    Accept-Language: "null"
    Authorization: "null"
    Cache-Control: "null"
    Connection: "null"
    Content-Length: "null"
    Content-Type: "null"
    Host: "{{host}}"                        #调用host
    Origin: "null"
    Pragma: "null"
    Referer: "null"
    User-Agent: "null"
    Cookie: "null"
    Proxy-Connection: "null"
  expression:                                 #匹配返回的信息
    code: 200                                 #请求返回的状态码status_code
    header: Apache                            #请求返回的header
    body: "version"                           #请求返回的body
  output: "cms:zentao-01"
- method: POST
  path: "{{host}}/login.jsp"                 #调用host
  follow_redirects: false
  body: |                                     #请求体
    "user=i11us0ry&&pass=i11us0ry"
  expression:
    code: 200
    body: "success"
  output: "login success"